# Generated by Django 4.1 on 2022-08-20 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('lineOfBus', models.CharField(choices=[('UMB', 'Umbrella'), ('AUT', 'Auto'), ('HOM', 'Home')], max_length=20)),
                ('policyterm', models.CharField(choices=[('Querterly', '3-Months'), ('Semi-Annual', '6-months'), ('Annual', '12-Months')], max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleYear', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('vehicleMake', models.CharField(max_length=20)),
                ('vehicleMod', models.CharField(max_length=50)),
                ('annualMileage', models.CharField(max_length=5)),
                ('garagingZipCode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.quotemodel')),
            ],
        ),
        migrations.CreateModel(
            name='incidentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentDate', models.DateField()),
                ('incidentType', models.CharField(max_length=9)),
                ('involvedDriverName', models.CharField(max_length=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.quotemodel')),
            ],
        ),
        migrations.CreateModel(
            name='driverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('drivingExperience', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('ageYears', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('drivingCourse', models.BooleanField(blank=True, default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.quotemodel')),
            ],
        ),
    ]
