# Generated by Django 4.1 on 2022-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackpagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Feedback', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='homepagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidentmodel',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='quote',
        ),
        migrations.DeleteModel(
            name='driverModel',
        ),
        migrations.DeleteModel(
            name='incidentModel',
        ),
        migrations.DeleteModel(
            name='quoteModel',
        ),
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
