cov_mapping = {
        'UMPD': 'UninsuredMotoristPD',
        'BI': 'BodilyInjury',
        'PD': 'PropertyDamage',
        'UM': 'UninsuredMotoristBI',
        'MED': 'Medical',
        'COMP': 'Comprehensive',
        'COLL': 'Collission',
        'ADD EQUI': 'AdditionaEquipment',
        'RENTAL RE': 'RentalReembursement',
        'LOSS OF USE': 'LossOfUse',
        'TOWING': 'Towing',
        'TOW': 'Towing',
        'ALL OTHER COVERAGES': 'Other',
        'RENT': 'RentalReembursement',
        'All': 'All'
    }

ratevars = [
        'TermLength',
        'UMPDOption',
        'DPS',
        'Symbol',
        'ModelYear ',
        'HighPerfInd ',
        'VehHistInd ',
        'PassiveResType',
        'AntiLockInd ',
        'AntitheftInd',
        'AltFuelInd ',
        'EscInd ',
        'DriverClass',
        'YearsDrivingExperience',
        'StudentAwayInd',
        'VehUseCode',
        'HouseholdCompostion',
        'FrequencyBand',
        'SeverityBand',
        'MultiPolicy',
        'GoodDriverDiscInd',
        'PermissiveUserOption',
        'VehicleAge1',
        'RideShareInd',
        'Deductible1',
        'Deductible2',
        'DriverClassCode',
        'VehicleAge2',
        'Limit1',
        'Limit2',
        'Mielage1',
        'Mileage2']
